project:
  type: website
  output-dir: ./_build
  render:
    - "*.qmd"
  resources:
    - "img/**/*"
    - "site_libs/**/*"
  preview:
    port: 3000
    browser: true

website:
  title: "Hermeneutik - Seminar"
  navbar:
    background: "#003366"
    search: true
    left:
      - text: "Startseite"
        href: index.html
      - text: "Sitzungen"
        href: sitzung.html
  sidebar:
    style: docked
    search: true
    contents:
      - section: "**Überblick**"
        contents:
          - index.qmd
      - section: "**Seminar-Protokolle**"
        contents:
          - sitzung.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    fig-width: 8
    fig-height: 6
    fig-format: svg
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    
bibliography: references.bib
